import = ["~/.config/alacritty/tokyonight-moon.toml"]

[env]
TERM = "xterm-256color"

[shell]
program = "tmux"

[window]
decorations = "none"

[font]
normal.family = "JetBrainsMono Nerd Font Mono"
size = 10.5
