set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

set -g base-index 1

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
