set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-ghostty:RGB"

set -g base-index 1
set -g pane-base-index 1

set -g mouse on

set-option -sg escape-time 10

set-option -g focus-events on

run-shell ~/.tmux/vim-tmux-navigator/vim-tmux-navigator.tmux
